site_name: Estrutura de Projetos do Zero
theme:
  name: material # or other theme
  palette:
    primary: blue
  language: en

repo_name: "joaobarreto27/como-estruturar-projeto-do-zero"
repo_url: "https://github.com/joaobarreto27/como_estruturar_projeto_do_zero"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - mermaid2
